FROM python:3.10-alpine

RUN useradd --create-home userapi
WORKDIR /films_api

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install pytest
COPY ./ .

RUN chown -R userapi:userapi ./
USER userapi

#RUN ["pytest", "-v", "--junitxml=reports/result.xml"]
CMD tail -f /dev/null