apiVersion: apps/v1
kind: Deployment
metadata:
  name: films-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
        - name: film-api
          image: film-api-image
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: film-api-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 32001